import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:velan_spaces_flutter/domain/entities/project_entity.dart';
import 'package:velan_spaces_flutter/presentation/providers/project_providers.dart';

class CreateProjectScreen extends ConsumerStatefulWidget {
  const CreateProjectScreen({super.key});

  @override
  ConsumerState<CreateProjectScreen> createState() => _CreateProjectScreenState();
}

class _CreateProjectScreenState extends ConsumerState<CreateProjectScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _clientController = TextEditingController();
  final _locationController = TextEditingController();
  final _budgetController = TextEditingController();

  @override
  void dispose() {
    _nameController.dispose();
    _clientController.dispose();
    _locationController.dispose();
    _budgetController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    ref.listen<AsyncValue<String?>>(projectCreationNotifierProvider, (previous, next) {
      next.whenOrNull(
        data: (projectId) {
          if (projectId != null) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Project created successfully!'), backgroundColor: Colors.green),
            );
            // Pop the screen on success
            if (context.canPop()) {
              context.pop();
            }
          }
        },
        error: (err, stack) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Error: $err'), backgroundColor: Colors.red),
          );
        },
      );
    });

    final creationState = ref.watch(projectCreationNotifierProvider);

    return Scaffold(
      appBar: AppBar(title: const Text('Create New Project')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(labelText: 'Project Name'),
                validator: (value) => (value?.isEmpty ?? true) ? 'This field cannot be empty' : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _clientController,
                decoration: const InputDecoration(labelText: 'Client Name'),
                 validator: (value) => (value?.isEmpty ?? true) ? 'This field cannot be empty' : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _locationController,
                decoration: const InputDecoration(labelText: 'Location'),
                 validator: (value) => (value?.isEmpty ?? true) ? 'This field cannot be empty' : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _budgetController,
                decoration: const InputDecoration(labelText: 'Budget (₹)'),
                keyboardType: TextInputType.number,
                 validator: (value) => (value?.isEmpty ?? true) ? 'This field cannot be empty' : null,
              ),
              const SizedBox(height: 32),
              ElevatedButton(
                onPressed: creationState.isLoading ? null : _createProject,
                style: ElevatedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 16),
                ),
                child: creationState.isLoading
                    ? const CircularProgressIndicator(color: Colors.white)
                    : const Text('Create Project'),
              ),
            ],
          ),
        ),
      ),
    );
  }

  void _createProject() {
    if (_formKey.currentState!.validate()) {
      // Get the current user's ID to assign as a manager
      // In a real scenario, you'd have a more robust way to select managers.
      // final currentUserId = ref.read(authStateChangesProvider).value?.uid;

      final project = ProjectEntity(
        id: '', // ID is generated by Firestore, so we pass an empty string.
        projectName: _nameController.text,
        clientName: _clientController.text,
        location: _locationController.text,
        budget: double.tryParse(_budgetController.text) ?? 0.0,
        currentSpend: 0.0,
        isComplete: false,
        managerIds: [], // Manager assignment can be a separate feature
      );
      ref.read(projectCreationNotifierProvider.notifier).createProject(project);
    }
  }
}
