import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:velan_spaces_flutter/domain/entities/manager_entity.dart';
import 'package:velan_spaces_flutter/domain/entities/worker_entity.dart';
import 'package:velan_spaces_flutter/presentation/providers/auth_providers.dart';

import 'package:velan_spaces_flutter/data/models/worker_model.dart';
import 'package:velan_spaces_flutter/data/datasources/worker_manager_datasource.dart';

final allManagersProvider = StreamProvider<List<ManagerEntity>>((ref) {
  final ds = ref.watch(workerManagerDatasourceProvider);
  return ds.watchAllManagers();
});

final allWorkersProvider = StreamProvider<List<WorkerEntity>>((ref) {
  final ds = ref.watch(workerManagerDatasourceProvider);
  return ds.watchAllWorkers();
});

final workerManagerControllerProvider =
    StateNotifierProvider<WorkerManagerController, AsyncValue<void>>((ref) {
  return WorkerManagerController(ref);
});

class WorkerManagerController extends StateNotifier<AsyncValue<void>> {
  final Ref _ref;

  WorkerManagerController(this._ref) : super(const AsyncValue.data(null));

  WorkerManagerDatasource get _datasource =>
      _ref.read(workerManagerDatasourceProvider);

  Future<bool> addWorker({
    required String name,
    String? phone,
    String? trade,
    String? assignToProjectId,
  }) async {
    state = const AsyncValue.loading();
    try {
      final assignedProjects =
          assignToProjectId != null ? [assignToProjectId] : <String>[];

      final worker = WorkerModel(
        id: '', // ID will be generated by Firestore
        name: name,
        phone: phone ?? '',
        trade: trade ?? '',
        assignedProjects: assignedProjects,
      );

      // 1. Create Create Worker
      final workerId = await _datasource.addWorker(worker);

      // 2. If project ID is provided, update the project's workerIds
      if (assignToProjectId != null) {
        final projectDs = _ref.read(firestoreProjectDatasourceProvider);
        // We need to use FieldValue.arrayUnion, but ProjectDatasource.updateProject takes generic map.
        // We assume the datasource implementation handles Map<String, dynamic> passed to update().
        // Firestore allows FieldValue in update().
        await projectDs.updateProject(assignToProjectId, {
          'workerIds': FieldValue.arrayUnion([workerId]),
        });
      }

      state = const AsyncValue.data(null);
      return true;
    } catch (e, st) {
      state = AsyncValue.error(e, st);
      return false;
    }
  }
}
